name: "Issue Sync"
author: "Christian Toney"
description: "Sync issues between GitHub and Discord."
inputs:
  github-token:
    description: "Token provided by GitHub."
    required: true
  discord-token:
    description: "Token of Discord bot account."
    required: true
  discord-channel-id:
    description: "ID of Discord channel to post to."
    required: true
  project-id:
    description: "ID of project to listen to."
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
